import { readFileSync, writeFileSync } from 'node:fs';
import { execSync } from 'node:child_process';

const muts = [
  ['cached cost beats live source', 'src/domain/costing.ts',
    'if (line.ingredient) {\n        ingredientBatch += ingredientCostFromSource(line.ingredient, line.quantity, line.unit);',
    'if (line.ingredient && !isNonNegative(line.cachedCost)) {\n        ingredientBatch += ingredientCostFromSource(line.ingredient, line.quantity, line.unit);'],
  ['per-portion packaging divided by yield again', 'src/domain/costing.ts',
    "if (line.semantics === 'per_portion') packagingPerPortion += cost;",
    "if (line.semantics === 'per_portion') packagingPerPortion += yieldOk ? cost / menu.yield : cost;"],
  ['missing sales treated as zero overhead', 'src/domain/operating.ts',
    "return { ok: false, reason: 'expected_sales_missing' };\n  }\n  assertAmount",
    "return { ok: true, rate: 0, ratePct: 0 };\n  }\n  assertAmount"],
  ['price change on sticker price not unit cost', 'src/domain/priceChange.ts',
    'percentChange: p.perBaseUnit > 0 ? ((c.perBaseUnit - p.perBaseUnit) / p.perBaseUnit) * 100 : null,',
    'percentChange: previous.purchasePrice > 0 ? ((current.purchasePrice - previous.purchasePrice) / previous.purchasePrice) * 100 : null,'],
  ['negative sign dropped in display', 'src/domain/format.ts',
    "const sign = value < 0 && rounded !== 0 ? MINUS : '';\n  return `${sign}RM",
    "const sign = '';\n  return `${sign}RM"],
  ['loss no longer overrides margin band', 'src/domain/status.ts',
    "if (profit < -EPSILON) return 'loss';\n  if (marginPct < thresholds.lowBelow - EPSILON) return 'low';",
    "if (marginPct < thresholds.lowBelow - EPSILON) return 'low';\n  if (profit < -EPSILON) return 'loss';"],
  ['direct utilities still counted as shared', 'src/domain/operating.ts',
    ".filter((e) => e.active && e.classification === 'shared')",
    '.filter((e) => e.active)'],
  ['switching mode wipes advanced detail', 'src/domain/operating.ts',
    'return { ...entry, mode };',
    'return { ...entry, mode, detail: undefined };'],
  ['scenario mutates live ingredient', 'src/domain/scenario.ts',
    'return { ...source, purchasePrice: (source.purchasePrice * (100 + pct)) / 100 };',
    'source.purchasePrice = (source.purchasePrice * (100 + pct)) / 100; return source;'],
  ['labour divided by 100 instead of 60', 'src/domain/costing.ts',
    'return (productionMinutes / 60) * valueOfTimePerHour;',
    'return (productionMinutes / 100) * valueOfTimePerHour;'],
  ['incompatible units converted silently', 'src/domain/units.ts',
    "throw new UnitError('incompatible', `Cannot convert ${from} to ${to}`);",
    'return quantity;'],
  ['floor-area uses wrong ratio', 'src/domain/operating.ts',
    'return (businessArea / homeArea) * 100;',
    'return (homeArea / businessArea) * 100;'],
  ['name-only edit writes a history record', 'src/domain/priceHistory.ts',
    "mappingsKey(previous.packMappings) !== mappingsKey(next.packMappings)\n  );",
    "mappingsKey(previous.packMappings) !== mappingsKey(next.packMappings)\n  ) || true;"],
  ['package-size change ignored by history', 'src/domain/priceHistory.ts',
    'previous.packageQuantity !== next.packageQuantity ||', ''],
  ['history compares out of order', 'src/domain/priceHistory.ts',
    'a.purchaseDate < b.purchaseDate ? -1 : a.purchaseDate > b.purchaseDate ? 1 : a.seq - b.seq',
    'a.seq - b.seq'],
  ['no baseline record on create', 'src/db/repo.ts',
    "await db.priceHistory.add(\n      historyRecord(ctx, ingredient.id, 1,",
    "if (false) await db.priceHistory.add(\n      historyRecord(ctx, ingredient.id, 1,"],
  ['backfill not idempotent', 'src/db/repo.ts',
    '.count()) > 0) continue;', '.count()) > 99) continue;'],
  ['history immutability hook removed', 'src/db/db.ts',
    "this.priceHistory.hook('deleting', () => {\n      if (this.restoring) return;\n      throw new ImmutableRecordError('priceHistory');\n    });",
    ''],
  ['duplicate operating category allowed', 'src/db/db.ts',
    "operatingCosts: 'id, &[businessId+category]'", "operatingCosts: 'id, [businessId+category]'"],
  ['operating save creates a new row every time', 'src/db/repo.ts',
    'id: existing?.id ?? ctx.newId(),', 'id: ctx.newId(),'],
  ['editing wattage no longer confirms equipment', 'src/db/masterData.ts',
    'requireWatts(patch.powerWatts), confirmed: true }', 'requireWatts(patch.powerWatts) }'],
  ['custom equipment left unconfirmed', 'src/db/masterData.ts',
    "source: 'user',\n    confirmed: true,", "source: 'user',\n    confirmed: false,"],
  ['preset seeding overwrites existing presets', 'src/db/masterData.ts',
    'await db.equipmentPresets.bulkAdd(missing);', 'await db.equipmentPresets.bulkPut(EQUIPMENT_PRESET_DEFAULTS);'],
  ['zero quantity accepted in forms', 'src/app/forms.ts',
    'return n !== null && n > 0 ? n : null;', 'return n !== null && n >= 0 ? n : null;'],
  ['thousands comma misread', 'src/app/forms.ts',
    '(,\\d{3})+$/.test(s)', '(,\\d{2})+$/.test(s)'],
  ['tiny unit cost shown as RM0.00', 'src/app/forms.ts',
    'shown.amount > 0 && shown.amount < 0.01', 'shown.amount > 0 && shown.amount < 0.0000001'],
  ['pack-mapping change ignored by history', 'src/domain/priceHistory.ts',
    ' ||\n    mappingsKey(previous.packMappings) !== mappingsKey(next.packMappings)', ''],
  ['zero expected sales accepted by storage', 'src/db/settings.ts',
    '!Number.isFinite(sales) || sales <= 0', '!Number.isFinite(sales) || sales < 0'],
  ['zero expected sales accepted by the form', 'src/app/operatingForms.ts',
    'if (n === null || n <= 0) errors.sales', 'if (n === null || n < 0) errors.sales'],
  ['same-date tariff piles up rows', 'src/db/settings.ts',
    'id: sameDay?.id ?? ctx.newId()', 'id: ctx.newId()'],
  ['future tariff treated as current', 'src/db/settings.ts',
    'r.effectiveDate <= today', 'true'],
  ['reset wipes the simple amount', 'src/db/settings.ts',
    "mode: 'simple', updatedAt", "mode: 'simple', simpleAmount: 0, updatedAt"],
  ['overview hides broken rows from allocation', 'src/app/operatingView.ts',
    "hasErrors ? { ok: false, reason: 'incomplete_costs' } : a", 'a'],
  ['workspace method flag ignored by engine', 'src/domain/operating.ts',
    "detail.method === 'area' || (detail.method === undefined && hasAreas)", 'hasAreas'],
  ['getter writes inside live query', 'src/db/settings.ts',
    'const business = await getBusiness(ctx);\n  const profile', 'const business = await ensureBusiness(ctx);\n  const profile'],
  ['missing Nilai Masa ignored by engine', 'src/domain/costing.ts',
    'business.valueOfTimePerHour === null && isPositive(menu.productionMinutesPerBatch)', 'false'],
  ['missing tariff ignored by engine', 'src/domain/costing.ts',
    'business.electricityTariffPerKwh === null && known.some', 'false && known.some'],
  ['missing packaging silently skipped', 'src/domain/costing.ts',
    "issues.push(issue('packaging_missing', line.ref));\n      packagingOk = false;", ''],
  ['missing equipment silently skipped', 'src/domain/costing.ts',
    "issues.push(issue('equipment_missing', l.ref));\n        utilitiesOk = false;", ''],
  ['broken Kos Operasi row read as zero overhead', 'src/app/menuAssembly.ts',
    'shared = null;', 'shared = 0;'],
  ['menu lines lose their order', 'src/db/menus.ts',
    'ingredients: [...ing].sort(byPosition).map(', 'ingredients: [...ing].reverse().map('],
  ['menu update leaves old ingredient rows behind', 'src/db/menus.ts',
    "await db.recipeIngredients.where('recipeId').equals(recipe.id).delete();", ''],
  ['labour explained with wrong divisor', 'src/app/menuExplain.ts',
    '(menu.productionMinutesPerBatch / 60) * rate', '(menu.productionMinutesPerBatch / 100) * rate'],
  ['zero yield accepted by the menu form', 'src/app/menuForm.ts',
    'yieldN === null || yieldN <= 0', 'yieldN === null || yieldN < 0'],
  ['ranking worst margin first', 'src/app/insights.ts',
    'b.marginPct - a.marginPct ||', 'a.marginPct - b.marginPct ||'],
  ['drops below the threshold never alert', 'src/app/insights.ts',
    'Math.abs(pct) < PRICE_ALERT_PCT', 'pct < PRICE_ALERT_PCT'],
  ['alert for an ingredient no menu uses', 'src/app/insights.ts',
    'if (trail.affectedMenus.length === 0) continue;', ''],
  ['affected menus miscounted', 'src/app/insights.ts',
    'm.ingredients.some((l) => l.ingredientId === ingredientId)', 'm.ingredients.every((l) => l.ingredientId === ingredientId)'],
  ['Jejak Harga oldest change first', 'src/app/insights.ts',
    'da < db ? 1 : -1', 'da < db ? -1 : 1'],
  ['several loss menus link to one arbitrary menu', 'src/app/insights.ts',
    'loss.length === 1 ? `/menu/${loss[0]!.id}` : \'/menu\'', '`/menu/${loss[0]!.id}`'],
  ['direction sign dropped from movement', 'src/app/signed.ts',
    'return value > 0 && !text.startsWith', 'return false && !text.startsWith'],
  ['closed alert ignored', 'src/app/insights.ts',
    'if (dismissed.has(key)) continue;', ''],
  ['alert key not tied to the price event', 'src/app/insights.ts',
    'const key = `price:${trail.ingredient.id}:${c.entry.id}`;', 'const key = `price:${trail.ingredient.id}`;'],
  ['trend y not inverted', 'src/app/trend.ts',
    '(1 - (p.amount - lo) / span) * h', '((p.amount - lo) / span) * h'],
  ['preview price not rounded to the sen', 'src/domain/scenario.ts',
    'return Math.round((raw + Number.EPSILON * Math.max(1, raw)) * 100) / 100;', 'return raw;'],
  ['history review ignores the earlier version', 'src/domain/scenario.ts',
    'before: computeMenuCost(withVersion(before), business, thresholds),', 'before: computeMenuCost(menu, business, thresholds),'],
  ['history review uses typing order, not purchase date', 'src/app/scenarioView.ts',
    'sortHistory(history.filter((r) => r.ingredientId === ingredientId))', 'history.filter((r) => r.ingredientId === ingredientId).sort((a, b) => a.seq - b.seq)'],
  ['history review compares with the wrong record', 'src/app/scenarioView.ts',
    'const previous = ordered[index - 1];', 'const previous = ordered[index + 1];'],
  ['what-if lists menus that do not use the ingredient', 'src/app/scenarioView.ts',
    '.filter((m) => m.active && m.ingredients.some((l) => l.ingredientId === ingredient.id))', '.filter((m) => m.active)'],
  ['a percentage of −100 or below accepted', 'src/app/scenarioView.ts',
    'return n > -100 ?', 'return n > -1000 ?'],
  ['backup checksum not verified', 'src/db/backup.ts',
    "if (parsed.checksum !== (await sha256(JSON.stringify(parsed.data)))) {", 'if (false) {'],
  ['backup references not checked', 'src/db/backup.ts',
    'if (!valid.has(row[field] as string))', 'if (false)'],
  ['restore merges instead of replacing', 'src/db/backup.ts',
    'for (const name of TABLES) await db[name].clear();', ''],
  ['newer backup format accepted', 'src/db/backup.ts',
    'parsed.format > BACKUP_FORMAT', 'parsed.format > 99'],
  ['price-history guard left open after restore', 'src/db/db.ts',
    'if (this.restoring) return;', 'return;'],
  ['negative amounts accepted from a backup', 'src/db/backup.ts',
    "(row[field] as number) < 0) issues.push({ code: 'bad_row', detail: `${name}[${i}].${field}` });\n      for (const field of POSITIVE)", "(row[field] as number) < -1e9) issues.push({ code: 'bad_row', detail: `${name}[${i}].${field}` });\n      for (const field of POSITIVE)"],
  ['reminder waits one day too long', 'src/app/backupReminder.ts',
    'days >= BACKUP_REMINDER_DAYS', 'days > BACKUP_REMINDER_DAYS'],
  ['free limit off by one', 'src/license/entitlement.ts',
    "currentCount < FREE_LIMITS[kind]", "currentCount <= FREE_LIMITS[kind]"],
  ['free plan gets detailed operating costs', 'src/license/entitlement.ts',
    "canUseDetailedOperating = (plan: Plan): boolean => plan === 'pro'", "canUseDetailedOperating = (plan: Plan): boolean => true"],
  ['token for another device accepted', 'src/license/token.ts',
    "if (p.deviceId !== deviceId)", "if (false)"],
  ['token signature not checked', 'src/license/token.ts',
    "if (!valid) return { ok: false, reason: 'bad_signature' };", ""],
  ['ambiguous characters allowed in codes', 'src/license/code.ts',
    "'ABCDEFGHJKMNPQRSTVWXYZ23456789'", "'ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789'"],
  ['callback hash not checked', 'server/core/api.ts',
    "if (!safeEqual(hash.toLowerCase(), md5(config.toyyibSecret + status + orderId + refno + 'ok')))", "if (false)"],
  ['payment not confirmed with ToyyibPay', 'server/core/api.ts',
    "if (!confirmed) return new Response('OK');", ""],
  ['paid amount not compared', 'server/core/api.ts',
    " && t.amountSen === order.amountSen", ""],
  ['third device allowed', 'server/core/api.ts',
    "devices.length >= config.maxDevices", "devices.length > config.maxDevices"],
  ['revoked code still activates', 'server/core/api.ts',
    "if (license.status === 'revoked') return json(403, { error: 'revoked' });", ""],
  ['wrong codes not counted for rate limit', 'server/core/api.ts',
    "await store.recordFailure(key, deps.now().toISOString());\n      return json(404, { error: 'invalid_code' });\n    }\n    if (license.status", "return json(404, { error: 'invalid_code' });\n    }\n    if (license.status"],
  ['rate limit one attempt too generous', 'server/core/api.ts',
    ">= config.failureLimit", "> config.failureLimit"],
  ['admin endpoints open without token', 'server/core/api.ts',
    "!safeEqual(auth, `Bearer ${config.adminToken}`)", "false"],
  ['double payment issues two licences (D1)', 'server/worker/d1Store.ts',
    " AND license_code IS NULL", ""],
];

const only = process.env.ONLY ? new RegExp(process.env.ONLY, 'i') : null;
let survived = 0;
let ran = 0;
for (const [name, file, from, to] of muts) {
  if (only && !only.test(name + ' ' + file)) continue;
  ran++;
  const original = readFileSync(file, 'utf8');
  if (!original.includes(from)) { console.log(`?? pattern not found: ${name}`); survived++; continue; }
  writeFileSync(file, original.replace(from, to));
  let killed = false;
  try { execSync('npx vitest run', { stdio: 'pipe' }); } catch { killed = true; }
  writeFileSync(file, original);
  if (!killed) survived++;
  console.log(`${killed ? 'KILLED  ' : 'SURVIVED'}  ${name}`);
}
console.log(`\n${ran - survived}/${ran} mutations caught`);
